### ISSUE TITLE
sidekiq expects /var/www/lagotto/ with subdirs to exist

### ISSUE THREAD

**Issue by lsh-0** [articlemetrics/lagotto#244]
I've had Lagotto installed to `/srv/lagotto` without problems, however after an upgrade Sidekiq is looking for things in `/var/www/lagotto/` and failing to start if they're not found.

Sidekiq should be adding it's logs to `<install>/log/` and it's pids to `<install>/sidekiq/` or similar - somewhere within the project dir.

```
$ rake sidekiq:start
No such file or directory @ rb_sysopen - /var/www/lagotto/shared/log/sidekiq.log
/usr/lib/ruby/2.1.0/logger.rb:600:in `initialize'
/usr/lib/ruby/2.1.0/logger.rb:600:in `open'
/usr/lib/ruby/2.1.0/logger.rb:600:in `create_logfile'
/usr/lib/ruby/2.1.0/logger.rb:594:in `rescue in open_logfile'
/usr/lib/ruby/2.1.0/logger.rb:591:in `open_logfile'
/usr/lib/ruby/2.1.0/logger.rb:549:in `initialize'
/usr/lib/ruby/2.1.0/logger.rb:318:in `new'
/usr/lib/ruby/2.1.0/logger.rb:318:in `initialize'
/var/lib/gems/2.1.0/gems/sidekiq-3.3.2/lib/sidekiq/logging.rb:31:in `new'
/var/lib/gems/2.1.0/gems/sidekiq-3.3.2/lib/sidekiq/logging.rb:31:in `initialize_logger'
/var/lib/gems/2.1.0/gems/sidekiq-3.3.2/lib/sidekiq/cli.rb:339:in `initialize_logger'
/var/lib/gems/2.1.0/gems/sidekiq-3.3.2/lib/sidekiq/cli.rb:39:in `parse'
/var/lib/gems/2.1.0/gems/sidekiq-3.3.2/bin/sidekiq:7:in `<top (required)>'
/usr/local/bin/sidekiq:23:in `load'
/usr/local/bin/sidekiq:23:in `<main>'
No Sidekiq process running, Sidekiq process started at 2015-02-10T12:54:13Z.
```

But with no process listed. With a `mkdir -p /var/www/lagotto/shared/log/ && chown -R elife:elife /var/www/` I get:

```
$ rake sidekiq:start
No Sidekiq process running, Sidekiq process started at 2015-02-10T13:04:09Z.
```

with the log file at `/var/www/lagotto/shared/log/sidekiq.log` showing:
```
No such file or directory @ rb_sysopen - /var/www/lagotto/shared/tmp/pids/sidekiq.pid
/var/lib/gems/2.1.0/gems/sidekiq-3.3.2/lib/sidekiq/cli.rb:347:in `initialize'
/var/lib/gems/2.1.0/gems/sidekiq-3.3.2/lib/sidekiq/cli.rb:347:in `open'
/var/lib/gems/2.1.0/gems/sidekiq-3.3.2/lib/sidekiq/cli.rb:347:in `write_pid'
/var/lib/gems/2.1.0/gems/sidekiq-3.3.2/lib/sidekiq/cli.rb:42:in `parse'
/var/lib/gems/2.1.0/gems/sidekiq-3.3.2/bin/sidekiq:7:in `<top (required)>'
/usr/local/bin/sidekiq:23:in `load'
/usr/local/bin/sidekiq:23:in `<main>'
```
so with a `mkdir -p /var/www/lagotto/shared/tmp/pids` and a `rake sidekiq:start` it finally starts working:
```
$ ps aux | grep -i side
elife    24856 85.4 21.2 1375644 435816 ?      Sl   13:04   5:56 sidekiq 3.3.2 lagotto [25 of 25 busy]
```

**Comment by mfenner** [comment]
This was fixed in #246.
