### ISSUE TITLE
"ActiveRecord::SubclassNotFound" error when running daily cron job

### ISSUE THREAD

**Issue by lsh-0** [articlemetrics/lagotto#250]
The daily cron job is giving an error that appears to be related to the database:
```
$ RAILS_ENV=production bundle exec rake cron:daily
rake aborted!
ActiveRecord::SubclassNotFound: The single-table inheritance mechanism failed to locate the subclass: 'ArticleNotUpdatedError'. This error is raised because the column 'type' is reserved for
 storing the class in case of inheritance. Please rename this column if you didn't intend it to be used for storing the inheritance class or overwrite Filter.inheritance_column to use anothe
r column for that information.   
/var/lib/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/inheritance.rb:186:in `rescue in find_sti_class'
/var/lib/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/inheritance.rb:180:in `find_sti_class'
/var/lib/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/inheritance.rb:169:in `discriminate_class_for_record'
/var/lib/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/persistence.rb:67:in `instantiate'
/var/lib/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/querying.rb:50:in `block (2 levels) in find_by_sql'
/var/lib/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/result.rb:51:in `block in each'
/var/lib/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/result.rb:51:in `each'
/var/lib/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/result.rb:51:in `each'
/var/lib/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/querying.rb:50:in `map'
/var/lib/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/querying.rb:50:in `block in find_by_sql'
/var/lib/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/var/lib/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/querying.rb:49:in `find_by_sql'
/var/lib/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/relation.rb:638:in `exec_queries'
/var/lib/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/relation.rb:514:in `load'
/var/lib/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/relation.rb:243:in `to_a'
/var/lib/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/relation/delegation.rb:46:in `each'
/srv/lagotto/app/models/filter.rb:43:in `run'
/srv/lagotto/lib/tasks/filter.rake:4:in `block (2 levels) in <top (required)>'
/srv/lagotto/lib/tasks/cron.rake:16:in `block (2 levels) in <top (required)>'
NameError: uninitialized constant ArticleNotUpdatedError
/var/lib/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/inflector/methods.rb:261:in `const_get'
/var/lib/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/inflector/methods.rb:261:in `block in constantize'
/var/lib/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/inflector/methods.rb:259:in `each'
/var/lib/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/inflector/methods.rb:259:in `inject'
/var/lib/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/inflector/methods.rb:259:in `constantize'
/var/lib/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/inheritance.rb:181:in `find_sti_class'
/var/lib/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/inheritance.rb:169:in `discriminate_class_for_record'
/var/lib/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/persistence.rb:67:in `instantiate'
/var/lib/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/querying.rb:50:in `block (2 levels) in find_by_sql'
/var/lib/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/result.rb:51:in `block in each'
/var/lib/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/result.rb:51:in `each'
/var/lib/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/result.rb:51:in `each'
/var/lib/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/querying.rb:50:in `map'
/var/lib/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/querying.rb:50:in `block in find_by_sql'
/var/lib/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/var/lib/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/querying.rb:49:in `find_by_sql'
/var/lib/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/relation.rb:638:in `exec_queries'
/var/lib/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/relation.rb:514:in `load'
/var/lib/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/relation.rb:243:in `to_a'
/var/lib/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/relation/delegation.rb:46:in `each'
/srv/lagotto/app/models/filter.rb:43:in `run'
/srv/lagotto/lib/tasks/filter.rake:4:in `block (2 levels) in <top (required)>'
/srv/lagotto/lib/tasks/cron.rake:16:in `block (2 levels) in <top (required)>'
Tasks: TOP => filter:all
(See full trace by running task with --trace)
```

All migrations have been run.

**Comment by mfenner** [comment]
This is (sort of) documented in the 3.10 release. Please run the following to rename the `ArticleNotUpdatedError` type column to `WorksNotUpdatedError`. You can of course also manually rename in MySQL.

```sh
RAILS_ENV=production bundle exec rake db:seed
```

**Comment by lsh-0** [comment]
no database migration for it?

On Wed, Feb 18, 2015 at 9:17 PM, Martin Fenner <notifications@github.com>
wrote:

> This is (sort of) documented in the 3.10 release. Please run the following
> to rename the ArticleNotUpdatedError type column to WorksNotUpdatedError.
> You can of course also manually rename in MySQL.
>
> RAILS_ENV=production bundle exec rake db:seed
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/articlemetrics/lagotto/issues/250#issuecomment-74949627>
> .
>



-- 

Luke Skibinski
devops - eLife

--

eLife Sciences Publications, Ltd is a limited liability non-profit
non-stock corporation incorporated in the State of Delaware, USA, with
company number 5030732, and is registered in the UK with company number
FC030576 and branch number BR015634 at the address First Floor, 24 Hills
Road, Cambridge CB2 1JP.

**Comment by mfenner** [comment]
No, we only change the data, not the database schema. And I don't like putting data into database migrations.

**Comment by lsh-0** [comment]
I've run the command and the daily cron appears to work now. There is a message though:

```
Both Source and its :state machine have defined a different default for "state". Use only one or the other for defining defaults to avoid unexpected behaviors.
```

If this is not a problem then close this issue.

Cheers,

**Comment by mfenner** [comment]
This is not a problem, you can ignore that warning.
